"""Generate a hierarchical root schematic referencing all sub-sheets.

This creates esp32-emu-turbo.kicad_sch as a root page that contains
(sheet ...) blocks pointing to each of the 7 sub-sheet files.
KiCad will then see all components across all sheets.
"""

from .kicad_primitives import KiCadContext


def generate_root(sheet_defs: list[dict]) -> str:
    """Generate root .kicad_sch with hierarchical sheet references."""
    ctx = KiCadContext()
    root_uuid = ctx.uid()

    parts = []
    parts.append(
        f'(kicad_sch\n'
        f'  (version 20231120)\n'
        f'  (generator "eeschema")\n'
        f'  (generator_version "9.0")\n'
        f'  (uuid "{root_uuid}")\n'
        f'  (paper "A2")\n'
        f'  (title_block\n'
        f'    (title "ESP32 Emu Turbo - Root Schematic")\n'
        f'    (comment 1 "Handheld Retro Console")\n'
        f'    (comment 2 "Generated by scripts/generate_schematics")\n'
        f'  )\n\n'
    )

    # Empty lib_symbols (sub-sheets carry their own)
    parts.append('  (lib_symbols\n  )\n\n')

    # Title text
    parts.append(ctx.text("ESP32 EMU TURBO", 50, 30, 6, True))
    parts.append(ctx.text(
        "Hierarchical root schematic - all sub-sheets linked below",
        50, 40, 2.54))

    # Generate sheet blocks in a 2-column grid
    sheet_uuids = []
    col_x = [40, 200]
    row_y_start = 60
    row_spacing = 45
    sheet_w = 120
    sheet_h = 30

    for i, sdef in enumerate(sheet_defs):
        col = i % 2
        row = i // 2
        sx = col_x[col]
        sy = row_y_start + row * row_spacing

        sheet_uuid = ctx.uid()
        sheet_uuids.append(sheet_uuid)

        filename = sdef["filename"]
        # Derive a clean sheet name from filename
        name = filename.replace(".kicad_sch", "").replace("-", " ").title()
        # Remove leading number
        if name[0:2].isdigit() or (name[0].isdigit() and name[1] == ' '):
            name = name.split(" ", 1)[-1] if " " in name else name

        parts.append(
            f'  (sheet (at {sx} {sy}) (size {sheet_w} {sheet_h})\n'
            f'    (stroke (width 0.001) (type solid))\n'
            f'    (fill (type none))\n'
            f'    (uuid "{sheet_uuid}")\n'
            f'    (property "Sheetname" "{name}"\n'
            f'      (at {sx + 2} {sy - 2} 0)\n'
            f'      (effects (font (size 1.27 1.27))))\n'
            f'    (property "Sheetfile" "{filename}"\n'
            f'      (at {sx + 2} {sy + sheet_h + 2} 0)\n'
            f'      (effects (font (size 1.27 1.27))))\n'
            f'  )\n'
        )

    # Sheet instances (required for KiCad to know page numbers)
    parts.append('\n  (sheet_instances\n')
    parts.append('    (path "/" (page "1"))\n')
    for i, suuid in enumerate(sheet_uuids):
        parts.append(f'    (path "/{suuid}" (page "{i + 2}"))\n')
    parts.append('  )\n')

    parts.append(')\n')
    return "".join(parts)
