"""Base class for KiCad schematic sheet generation."""

from .kicad_primitives import KiCadContext
from .lib_symbols import lib_symbols_block


class SchematicSheet:
    """Base class for a single KiCad schematic sheet (A4 landscape)."""

    title: str = "Untitled"
    page_number: int = 1
    paper: str = "A4"
    needed_symbols: list[str] = []

    def __init__(self, ctx: KiCadContext):
        self.ctx = ctx
        self.parts: list[str] = []

    def header(self) -> str:
        return (
            f'(kicad_sch\n'
            f'  (version 20231120)\n'
            f'  (generator "eeschema")\n'
            f'  (generator_version "9.0")\n'
            f'  (uuid "{self.ctx.uid()}")\n'
            f'  (paper "{self.paper}")\n'
            f'  (title_block\n'
            f'    (title "{self.title}")\n'
            f'    (comment 1 "ESP32 Emu Turbo - Handheld Retro Console")\n'
            f'    (comment 2 "Generated by scripts/generate_schematics")\n'
            f'  )\n\n'
        )

    def footer(self) -> str:
        return (
            f'\n  (sheet_instances (path "/" (page "{self.page_number}")))\n'
            f')\n'
        )

    def build(self):
        """Override in subclasses to populate self.parts."""
        raise NotImplementedError

    def render(self) -> str:
        """Generate the complete .kicad_sch content."""
        self.build()
        sections = [
            self.header(),
            lib_symbols_block(self.needed_symbols),
            "\n",
            "".join(self.parts),
            self.footer(),
        ]
        return "".join(sections)

    # Shortcuts delegating to ctx
    def wire(self, x1, y1, x2, y2):
        self.parts.append(self.ctx.wire(x1, y1, x2, y2))

    def label(self, name, x, y, angle=0):
        self.parts.append(self.ctx.label(name, x, y, angle))

    def glabel(self, name, x, y, angle=0, shape="bidirectional"):
        self.parts.append(self.ctx.global_label(name, x, y, angle, shape))

    def text(self, txt, x, y, sz=2.54, bold=False):
        self.parts.append(self.ctx.text(txt, x, y, sz, bold))

    def gnd(self, x, y):
        self.parts.append(self.ctx.gnd(x, y))

    def v33(self, x, y):
        self.parts.append(self.ctx.v33(x, y))

    def v5(self, x, y):
        self.parts.append(self.ctx.v5(x, y))

    def sym(self, lib, ref, val, x, y, pins):
        self.parts.append(self.ctx.symbol(lib, ref, val, x, y, pins))
