"""Base class for KiCad schematic sheet generation."""

import math
import re

from .kicad_primitives import KiCadContext
from .lib_symbols import lib_symbols_block


class SchematicSheet:
    """Base class for a single KiCad schematic sheet (A4 landscape)."""

    title: str = "Untitled"
    page_number: int = 1
    paper: str = "A4"
    needed_symbols: list[str] = []

    def __init__(self, ctx: KiCadContext):
        self.ctx = ctx
        self.parts: list[str] = []

    def header(self) -> str:
        return (
            f'(kicad_sch\n'
            f'  (version 20231120)\n'
            f'  (generator "eeschema")\n'
            f'  (generator_version "9.0")\n'
            f'  (uuid "{self.ctx.uid()}")\n'
            f'  (paper "{self.paper}")\n'
            f'  (title_block\n'
            f'    (title "{self.title}")\n'
            f'    (comment 1 "ESP32 Emu Turbo - Handheld Retro Console")\n'
            f'    (comment 2 "Generated by scripts/generate_schematics")\n'
            f'  )\n\n'
        )

    def footer(self) -> str:
        return (
            f'\n  (sheet_instances (path "/" (page "{self.page_number}")))\n'
            f')\n'
        )

    def build(self):
        """Override in subclasses to populate self.parts."""
        raise NotImplementedError

    def render(self) -> str:
        """Generate the complete .kicad_sch content."""
        self.build()
        self._split_wires_at_connection_points()
        sections = [
            self.header(),
            lib_symbols_block(self.needed_symbols),
            "\n",
            "".join(self.parts),
            self.footer(),
        ]
        return "".join(sections)

    # Wires must END at every point where something connects to them.
    # KiCad's GUI accepts a stub ending mid-span of a rail (with a
    # junction dot) or a label anchored mid-span, but the HEADLESS
    # netlisters do not agree on that construct across versions — on this
    # exact file kicad-cli 10.0 (macOS) netted it fully, 9.0.9 (Ubuntu)
    # split the rail around the junction, and nightly 9.99 dropped the
    # tapped pins entirely (C18.1/R16.1/C3.1 "unconnected"). A wire
    # *endpoint* meeting other wire endpoints is the one construct every
    # engine nets identically, so after build() every wire is split at
    # each junction, label, global-label or one-pin power-symbol anchor
    # lying strictly inside it. Sheets keep drawing full-span rails; this
    # pass makes the emitted geometry engine-invariant.
    _SPLIT_PT_RES = [
        re.compile(r'^  \(junction \(at ([\d.eE+-]+) ([\d.eE+-]+)\)'),
        re.compile(r'^  \(label "[^"]*" \(at ([\d.eE+-]+) ([\d.eE+-]+)'),
        re.compile(r'^  \(global_label "[^"]*" \(shape \w+\)'
                   r' \(at ([\d.eE+-]+) ([\d.eE+-]+)'),
        re.compile(r'^  \(symbol \(lib_id "(?:emu:)?(?:GND|\+3V3|\+5V|PWR_FLAG)"\)'
                   r' \(at ([\d.eE+-]+) ([\d.eE+-]+)'),
    ]
    _WIRE_RE = re.compile(
        r'^  \(wire \(pts \(xy ([\d.eE+-]+) ([\d.eE+-]+)\)'
        r' \(xy ([\d.eE+-]+) ([\d.eE+-]+)\)\)'
    )

    def _split_wires_at_connection_points(self):
        eps = 1e-4
        points = []
        for part in self.parts:
            for rx in self._SPLIT_PT_RES:
                m = rx.match(part)
                if m:
                    points.append((float(m.group(1)), float(m.group(2))))
                    break
        if not points:
            return
        out = []
        for part in self.parts:
            m = self._WIRE_RE.match(part)
            if not m:
                out.append(part)
                continue
            x1, y1, x2, y2 = (float(g) for g in m.groups())
            dx, dy = x2 - x1, y2 - y1
            length = math.hypot(dx, dy)
            cuts = []
            for px, py in points:
                # distance from the segment's line, then position along it
                if length < eps:
                    continue
                t = ((px - x1) * dx + (py - y1) * dy) / (length * length)
                if not (eps / length < t < 1 - eps / length):
                    continue
                ox, oy = x1 + t * dx - px, y1 + t * dy - py
                if math.hypot(ox, oy) < eps:
                    cuts.append((t, px, py))
            if not cuts:
                out.append(part)
                continue
            cuts.sort()
            prev = (x1, y1)
            for _t, px, py in cuts:
                out.append(self.ctx.wire(prev[0], prev[1], px, py))
                prev = (px, py)
            out.append(self.ctx.wire(prev[0], prev[1], x2, y2))
        self.parts = out

    # Shortcuts delegating to ctx
    def wire(self, x1, y1, x2, y2):
        self.parts.append(self.ctx.wire(x1, y1, x2, y2))

    def label(self, name, x, y, angle=0):
        self.parts.append(self.ctx.label(name, x, y, angle))

    def junction(self, x, y):
        self.parts.append(self.ctx.junction(x, y))

    def link(self, name, x, y, angle=0, stub=3.81, glob=False):
        """Connect a point to a net BY LABEL instead of by a drawn wire.

        Draws a short stub away from the pin and puts the net name on its
        end. Two link() calls with the same name are connected, with
        nothing drawn between them — so the connection cannot cross
        anything, and the sheet stays readable as signal count grows.

        Use this instead of routing a wire across the sheet. `angle` is the
        direction the stub points: 0 right, 90 up, 180 left, 270 down.

        Set `glob=True` when the net ALREADY carries a global label on this
        sheet. Mixing a local and a global label of the same name still
        connects, but KiCad raises `same_local_global_label` and the reader
        cannot tell which one is authoritative.
        """
        import math
        rad = math.radians(angle)
        ex = round(x + stub * math.cos(rad), 2)
        ey = round(y - stub * math.sin(rad), 2)
        self.wire(x, y, ex, ey)
        if glob:
            self.glabel(name, ex, ey, angle)
        else:
            self.label(name, ex, ey, angle)

    def glabel(self, name, x, y, angle=0, shape="bidirectional"):
        self.parts.append(self.ctx.global_label(name, x, y, angle, shape))

    def text(self, txt, x, y, sz=2.54, bold=False):
        self.parts.append(self.ctx.text(txt, x, y, sz, bold))

    def gnd(self, x, y):
        self.parts.append(self.ctx.gnd(x, y))

    def v33(self, x, y):
        self.parts.append(self.ctx.v33(x, y))

    def v5(self, x, y):
        self.parts.append(self.ctx.v5(x, y))

    def nc(self, x, y):
        self.parts.append(self.ctx.no_connect(x, y))

    def flag(self, x, y):
        self.parts.append(self.ctx.pwr_flag(x, y))

    def sym(self, lib, ref, val, x, y, pins, angle=0):
        self.parts.append(self.ctx.symbol(lib, ref, val, x, y, pins, angle))
