/*
 * ESP32 Emu Turbo — Hardware Test Suite
 * Auto-generated by scripts/generate_hw_tests.py on 2026-04-10 00:17:15
 *
 * Validates assembled PCB: buttons, LCD bus, SD, audio, USB, power, PSRAM.
 * Flash via: idf.py -C software build flash monitor
 * Results on USB-CDC serial console at 115200 baud.
 */

#include <stdio.h>
#include <string.h>

#include "unity.h"
#include "board_config.h"

#include "driver/gpio.h"
#include "driver/spi_master.h"
#include "driver/i2s_pdm.h"
#include "esp_heap_caps.h"
#include "esp_log.h"
#include "esp_adc/adc_oneshot.h"
#include "hal/usb_serial_jtag_ll.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

static const char *TAG = "hw_test";

/* ── Helpers ────────────────────────────────────────────────── */

static esp_err_t cfg_input(gpio_num_t pin, bool internal_pullup)
{
    gpio_config_t c = {
        .pin_bit_mask = 1ULL << pin,
        .mode         = GPIO_MODE_INPUT,
        .pull_up_en   = internal_pullup ? GPIO_PULLUP_ENABLE : GPIO_PULLUP_DISABLE,
        .pull_down_en = GPIO_PULLDOWN_DISABLE,
        .intr_type    = GPIO_INTR_DISABLE,
    };
    return gpio_config(&c);
}

static esp_err_t cfg_inout(gpio_num_t pin)
{
    gpio_config_t c = {
        .pin_bit_mask = 1ULL << pin,
        .mode         = GPIO_MODE_INPUT_OUTPUT,
        .pull_up_en   = GPIO_PULLUP_DISABLE,
        .pull_down_en = GPIO_PULLDOWN_DISABLE,
        .intr_type    = GPIO_INTR_DISABLE,
    };
    return gpio_config(&c);
}

/* ══════════════════════════════════════════════════════════════
 * 1. GPIO Button Tests — 12 buttons, active-low
 *    Each should read HIGH (1) when not pressed.
 * ══════════════════════════════════════════════════════════ */

static void test_btn_up(void)
{
    TEST_ASSERT_EQUAL(ESP_OK, cfg_input(BTN_UP, false));
    vTaskDelay(pdMS_TO_TICKS(10));
    TEST_ASSERT_EQUAL_MESSAGE(1, gpio_get_level(BTN_UP),
        "BTN_UP (GPIO40) stuck LOW — check solder/short");
}

static void test_btn_down(void)
{
    TEST_ASSERT_EQUAL(ESP_OK, cfg_input(BTN_DOWN, false));
    vTaskDelay(pdMS_TO_TICKS(10));
    TEST_ASSERT_EQUAL_MESSAGE(1, gpio_get_level(BTN_DOWN),
        "BTN_DOWN (GPIO41) stuck LOW — check solder/short");
}

static void test_btn_left(void)
{
    TEST_ASSERT_EQUAL(ESP_OK, cfg_input(BTN_LEFT, false));
    vTaskDelay(pdMS_TO_TICKS(10));
    TEST_ASSERT_EQUAL_MESSAGE(1, gpio_get_level(BTN_LEFT),
        "BTN_LEFT (GPIO42) stuck LOW — check solder/short");
}

static void test_btn_right(void)
{
    TEST_ASSERT_EQUAL(ESP_OK, cfg_input(BTN_RIGHT, false));
    vTaskDelay(pdMS_TO_TICKS(10));
    TEST_ASSERT_EQUAL_MESSAGE(1, gpio_get_level(BTN_RIGHT),
        "BTN_RIGHT (GPIO1) stuck LOW — check solder/short");
}

static void test_btn_a(void)
{
    TEST_ASSERT_EQUAL(ESP_OK, cfg_input(BTN_A, false));
    vTaskDelay(pdMS_TO_TICKS(10));
    TEST_ASSERT_EQUAL_MESSAGE(1, gpio_get_level(BTN_A),
        "BTN_A (GPIO2) stuck LOW — check solder/short");
}

static void test_btn_b(void)
{
    TEST_ASSERT_EQUAL(ESP_OK, cfg_input(BTN_B, false));
    vTaskDelay(pdMS_TO_TICKS(10));
    TEST_ASSERT_EQUAL_MESSAGE(1, gpio_get_level(BTN_B),
        "BTN_B (GPIO48) stuck LOW — check solder/short");
}

static void test_btn_x(void)
{
    TEST_ASSERT_EQUAL(ESP_OK, cfg_input(BTN_X, false));
    vTaskDelay(pdMS_TO_TICKS(10));
    TEST_ASSERT_EQUAL_MESSAGE(1, gpio_get_level(BTN_X),
        "BTN_X (GPIO47) stuck LOW — check solder/short");
}

static void test_btn_y(void)
{
    TEST_ASSERT_EQUAL(ESP_OK, cfg_input(BTN_Y, false));
    vTaskDelay(pdMS_TO_TICKS(10));
    TEST_ASSERT_EQUAL_MESSAGE(1, gpio_get_level(BTN_Y),
        "BTN_Y (GPIO21) stuck LOW — check solder/short");
}

static void test_btn_start(void)
{
    TEST_ASSERT_EQUAL(ESP_OK, cfg_input(BTN_START, false));
    vTaskDelay(pdMS_TO_TICKS(10));
    TEST_ASSERT_EQUAL_MESSAGE(1, gpio_get_level(BTN_START),
        "BTN_START (GPIO18) stuck LOW — check solder/short");
}

static void test_btn_select(void)
{
    TEST_ASSERT_EQUAL(ESP_OK, cfg_input(BTN_SELECT, false));
    vTaskDelay(pdMS_TO_TICKS(10));
    TEST_ASSERT_EQUAL_MESSAGE(1, gpio_get_level(BTN_SELECT),
        "BTN_SELECT (GPIO0) stuck LOW — check solder/short");
}

static void test_btn_l(void)
{
    TEST_ASSERT_EQUAL(ESP_OK, cfg_input(BTN_L, true));
    /* BTN_L uses internal pull-up (no external, VDD_SPI strap) */
    vTaskDelay(pdMS_TO_TICKS(10));
    TEST_ASSERT_EQUAL_MESSAGE(1, gpio_get_level(BTN_L),
        "BTN_L (GPIO45) stuck LOW — check solder/short");
}

static void test_btn_r(void)
{
    TEST_ASSERT_EQUAL(ESP_OK, cfg_input(BTN_R, false));
    vTaskDelay(pdMS_TO_TICKS(10));
    TEST_ASSERT_EQUAL_MESSAGE(1, gpio_get_level(BTN_R),
        "BTN_R (GPIO3) stuck LOW — check solder/short");
}

/* ══════════════════════════════════════════════════════════════
 * 2. LCD Data Bus — walking-1 test for shorts between D0-D7
 * ══════════════════════════════════════════════════════════ */

static void test_lcd_data_bus(void)
{
    const gpio_num_t d[] = { LCD_D0, LCD_D1, LCD_D2, LCD_D3, LCD_D4, LCD_D5, LCD_D6, LCD_D7 };
    const int n = 8;

    for (int i = 0; i < n; i++) {
        TEST_ASSERT_EQUAL(ESP_OK, cfg_inout(d[i]));
        gpio_set_level(d[i], 0);
    }
    vTaskDelay(pdMS_TO_TICKS(5));

    /* Walk a 1 across the bus, verify neighbors stay LOW */
    for (int i = 0; i < n; i++) {
        gpio_set_level(d[i], 1);
        vTaskDelay(pdMS_TO_TICKS(2));
        if (i > 0)
            TEST_ASSERT_EQUAL_MESSAGE(0, gpio_get_level(d[i-1]),
                "LCD bus short: adjacent lower pin HIGH");
        if (i < n - 1)
            TEST_ASSERT_EQUAL_MESSAGE(0, gpio_get_level(d[i+1]),
                "LCD bus short: adjacent upper pin HIGH");
        gpio_set_level(d[i], 0);
    }
}

/* ══════════════════════════════════════════════════════════════
 * 3. LCD Control — verify CS/RST/DC/WR can toggle
 * ══════════════════════════════════════════════════════════ */

static void test_lcd_control(void)
{
    const gpio_num_t pins[] = { LCD_CS, LCD_RST, LCD_DC, LCD_WR };
    const char *names[] = { "LCD_CS", "LCD_RST", "LCD_DC", "LCD_WR" };
    const int n = 4;

    for (int i = 0; i < n; i++) {
        TEST_ASSERT_EQUAL(ESP_OK, cfg_inout(pins[i]));

        gpio_set_level(pins[i], 1);
        vTaskDelay(pdMS_TO_TICKS(2));
        if (gpio_get_level(pins[i]) != 1)
            TEST_FAIL_MESSAGE("LCD ctrl pin stuck LOW");

        gpio_set_level(pins[i], 0);
        vTaskDelay(pdMS_TO_TICKS(2));
        if (gpio_get_level(pins[i]) != 0)
            TEST_FAIL_MESSAGE("LCD ctrl pin stuck HIGH");

        ESP_LOGI(TAG, "%s OK", names[i]);
    }
}

/* ══════════════════════════════════════════════════════════════
 * 4. SD Card SPI — init bus, send CMD0, verify response
 * ══════════════════════════════════════════════════════════ */

static void test_sd_spi(void)
{
    spi_bus_config_t bus = {
        .mosi_io_num     = SD_MOSI,
        .miso_io_num     = SD_MISO,
        .sclk_io_num     = SD_CLK,
        .quadwp_io_num   = -1,
        .quadhd_io_num   = -1,
        .max_transfer_sz = 4096,
    };
    esp_err_t ret = spi_bus_initialize(SD_SPI_HOST, &bus, SPI_DMA_CH_AUTO);
    TEST_ASSERT_MESSAGE(ret == ESP_OK || ret == ESP_ERR_INVALID_STATE,
        "SPI bus init failed — check MOSI/MISO/CLK GPIOs");

    spi_device_handle_t dev;
    spi_device_interface_config_t devcfg = {
        .clock_speed_hz = 400000,  /* 400 kHz for card init */
        .mode           = 0,
        .spics_io_num   = SD_CS,
        .queue_size     = 1,
    };
    TEST_ASSERT_EQUAL_MESSAGE(ESP_OK, spi_bus_add_device(SD_SPI_HOST, &devcfg, &dev),
        "SPI device add failed");

    /* Send CMD0 (GO_IDLE_STATE) — basic bus connectivity test */
    uint8_t cmd0[6] = {0x40, 0x00, 0x00, 0x00, 0x00, 0x95};
    uint8_t resp[6] = {0};
    spi_transaction_t txn = {
        .length    = 48,
        .tx_buffer = cmd0,
        .rx_buffer = resp,
    };
    TEST_ASSERT_EQUAL_MESSAGE(ESP_OK, spi_device_transmit(dev, &txn),
        "SPI transmit failed — wiring issue");
    ESP_LOGI(TAG, "SD CMD0 response: 0x%02x 0x%02x", resp[0], resp[1]);

    spi_bus_remove_device(dev);
    spi_bus_free(SD_SPI_HOST);
}

/* ══════════════════════════════════════════════════════════════
 * 5. I2S PDM TX — write 100 samples of silence, no error
 * ══════════════════════════════════════════════════════════ */

static void test_i2s_pdm(void)
{
    i2s_chan_handle_t tx = NULL;
    i2s_chan_config_t ch_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_0, I2S_ROLE_MASTER);
    TEST_ASSERT_EQUAL(ESP_OK, i2s_new_channel(&ch_cfg, &tx, NULL));

    i2s_pdm_tx_config_t pdm_cfg = {
        .clk_cfg  = I2S_PDM_TX_CLK_DEFAULT_CONFIG(AUDIO_SAMPLE_RATE),
        .slot_cfg = I2S_PDM_TX_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_16BIT,
                                                    I2S_SLOT_MODE_MONO),
        .gpio_cfg = {
            .clk  = I2S_BCLK,
            .dout = I2S_DOUT,
            .invert_flags = { .clk_inv = false },
        },
    };
    TEST_ASSERT_EQUAL(ESP_OK, i2s_channel_init_pdm_tx_channel(tx, &pdm_cfg));
    TEST_ASSERT_EQUAL(ESP_OK, i2s_channel_enable(tx));

    int16_t silence[100] = {0};
    size_t written = 0;
    esp_err_t ret = i2s_channel_write(tx, silence, sizeof(silence),
                                       &written, pdMS_TO_TICKS(500));
    TEST_ASSERT_EQUAL_MESSAGE(ESP_OK, ret, "I2S write error — check BCLK/DOUT wiring");
    TEST_ASSERT_GREATER_THAN_MESSAGE(0, (int)written, "Zero bytes written to I2S");
    ESP_LOGI(TAG, "I2S PDM: %d bytes written OK", (int)written);

    i2s_channel_disable(tx);
    i2s_del_channel(tx);
}

/* ══════════════════════════════════════════════════════════════
 * 6. USB — native USB Serial JTAG on GPIO19/20
 * ══════════════════════════════════════════════════════════ */

static void test_usb(void)
{
    TEST_ASSERT_EQUAL_MESSAGE(19, USB_DN, "USB D- must be GPIO19");
    TEST_ASSERT_EQUAL_MESSAGE(20, USB_DP, "USB D+ must be GPIO20");

    bool ok = usb_serial_jtag_ll_txfifo_writable();
    ESP_LOGI(TAG, "USB Serial JTAG FIFO writable: %s", ok ? "yes" : "no");
    TEST_ASSERT_TRUE_MESSAGE(ok, "USB Serial JTAG peripheral not responding");
}

/* ══════════════════════════════════════════════════════════════
 * 7. Power — 3.3V rail sanity via ADC
 * ══════════════════════════════════════════════════════════ */

static void test_power(void)
{
    adc_oneshot_unit_handle_t adc;
    adc_oneshot_unit_init_cfg_t init = {
        .unit_id  = ADC_UNIT_1,
        .ulp_mode = ADC_ULP_MODE_DISABLE,
    };
    TEST_ASSERT_EQUAL(ESP_OK, adc_oneshot_new_unit(&init, &adc));

    adc_oneshot_chan_cfg_t chan = {
        .atten    = ADC_ATTEN_DB_0,
        .bitwidth = ADC_BITWIDTH_12,
    };
    TEST_ASSERT_EQUAL(ESP_OK, adc_oneshot_config_channel(adc, ADC_CHANNEL_0, &chan));

    int raw = 0;
    TEST_ASSERT_EQUAL(ESP_OK, adc_oneshot_read(adc, ADC_CHANNEL_0, &raw));
    ESP_LOGI(TAG, "ADC1_CH0 raw=%d (3V3 rail OK if no brownout)", raw);

    TEST_ASSERT_GREATER_OR_EQUAL(0, raw);
    TEST_ASSERT_LESS_OR_EQUAL(4095, raw);

    adc_oneshot_del_unit(adc);
}

/* ══════════════════════════════════════════════════════════════
 * 8. LED — toggle for visual verification
 * ══════════════════════════════════════════════════════════ */

static void test_led(void)
{
    TEST_IGNORE_MESSAGE("LED1/LED2 not defined in board_config.h — skipped");
}

/* ══════════════════════════════════════════════════════════════
 * 9. PSRAM — allocate 1MB, write/read XOR pattern
 * ══════════════════════════════════════════════════════════ */

#define PSRAM_TEST_SIZE (1024 * 1024)  /* 1 MB */

static void test_psram(void)
{
    uint8_t *buf = heap_caps_malloc(PSRAM_TEST_SIZE, MALLOC_CAP_SPIRAM);
    TEST_ASSERT_NOT_NULL_MESSAGE(buf,
        "Failed to alloc 1MB from PSRAM — check Octal PSRAM config in menuconfig");

    /* Write: each byte = (offset & 0xFF) ^ 0xA5 */
    for (size_t i = 0; i < PSRAM_TEST_SIZE; i++)
        buf[i] = (uint8_t)((i & 0xFF) ^ 0xA5);

    /* Verify */
    int errs = 0;
    for (size_t i = 0; i < PSRAM_TEST_SIZE; i++) {
        uint8_t exp = (uint8_t)((i & 0xFF) ^ 0xA5);
        if (buf[i] != exp) {
            if (errs < 5)
                ESP_LOGE(TAG, "PSRAM @0x%06x: got 0x%02x want 0x%02x",
                         (unsigned)i, buf[i], exp);
            errs++;
        }
    }
    ESP_LOGI(TAG, "PSRAM 1MB check: %d errors", errs);
    TEST_ASSERT_EQUAL_MESSAGE(0, errs, "PSRAM data corruption detected");

    heap_caps_free(buf);
}

/* ══════════════════════════════════════════════════════════════
 * Test Runner
 * ══════════════════════════════════════════════════════════ */

void app_main(void)
{
    /* Allow USB-CDC console to connect */
    vTaskDelay(pdMS_TO_TICKS(2000));

    printf("\n");
    printf("╔══════════════════════════════════════════╗\n");
    printf("║  ESP32 Emu Turbo — Hardware Test Suite   ║\n");
    printf("╚══════════════════════════════════════════╝\n\n");

    UNITY_BEGIN();

    /* 1. Button idle-HIGH tests */
    RUN_TEST(test_btn_up);
    RUN_TEST(test_btn_down);
    RUN_TEST(test_btn_left);
    RUN_TEST(test_btn_right);
    RUN_TEST(test_btn_a);
    RUN_TEST(test_btn_b);
    RUN_TEST(test_btn_x);
    RUN_TEST(test_btn_y);
    RUN_TEST(test_btn_start);
    RUN_TEST(test_btn_select);
    RUN_TEST(test_btn_l);
    RUN_TEST(test_btn_r);

    /* 2. LCD data bus short detection */
    RUN_TEST(test_lcd_data_bus);

    /* 3. LCD control pin toggle */
    RUN_TEST(test_lcd_control);

    /* 4. SD card SPI bus */
    RUN_TEST(test_sd_spi);

    /* 5. I2S PDM audio output */
    RUN_TEST(test_i2s_pdm);

    /* 6. USB Serial JTAG */
    RUN_TEST(test_usb);

    /* 7. Power rail */
    RUN_TEST(test_power);

    /* 8. LED visual check */
    RUN_TEST(test_led);

    /* 9. PSRAM integrity */
    RUN_TEST(test_psram);

    UNITY_END();

    printf("\nDone. %d tests, %d failures, %d ignored.\n",
           Unity.NumberOfTests, Unity.TestFailures, Unity.TestIgnores);
    printf("Reboot to re-run.\n");
}
