#!/usr/bin/env python3
"""Emit the data file behind website/static/net-explorer.html.

The explorer answers one question: for a given pad on a given component,
where does the copper go? To do that it needs the whole conductor graph —
pads, tracks, vias, zones — plus enough footprint metadata to say which
side of the board a part is on.

The pad/track/via geometry comes from `pcb_cache` (the .kicad_pcb itself
is a token landmine — never read it directly). Footprint side, rotation
and value are not in the cache, so they are parsed here straight from the
board file, along with the Edge.Cuts outline used to draw the board.

Output: website/static/net-explorer-data.json

Usage:
    python3 scripts/generate_net_explorer.py           # regenerate
    python3 scripts/generate_net_explorer.py --check   # fail if stale

The explorer is documentation, so it obeys the same rule as the rest of
the docs: it is regenerated by `make generate-pcb` and the release
pipeline, and `--check` (wired into VERIFY_ALL_SCRIPTS) fails the build
whenever a track, a placement or a BOM field has moved and the shipped
JSON no longer matches the board.
"""
import json
import os
import re
import sys

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(PROJECT_DIR, "scripts"))

PCB = os.path.join(PROJECT_DIR, "hardware/kicad/esp32-emu-turbo.kicad_pcb")
OUT = os.path.join(PROJECT_DIR, "website/static/net-explorer-data.json")

COPPER_LAYERS = ["F.Cu", "In1.Cu", "In2.Cu", "B.Cu"]

# Douglas-Peucker tolerance for the zone fills. 0.02 mm is well under the
# 0.09 mm minimum clearance, so a simplified outline can never make two
# nets look closer than they are — this is for drawing, and every
# clearance judgement still belongs to verify_copper_clearance.py.
ZONE_SIMPLIFY_MM = 0.02

# ── functional sections ──────────────────────────────────────────────
#
# The explorer can isolate one functional block — charging, display,
# audio… — and dim everything else. Same shape as issue_dispatch's
# routing: a keyword law plus explicit exceptions, and anything the law
# does not cover is a HARD ERROR, not a default bucket. Adding a net to
# the board without giving it a section therefore fails `--check` (which
# is in VERIFY_ALL_SCRIPTS) instead of silently rendering as "no
# section".
#
# The power rails are deliberately NOT owned by any section: +3V3, +5V
# and GND touch every subsystem, so a section that included them would
# light the whole board and defeat the isolation.

RAIL_NETS = {"+3V3", "+5V", "GND"}

SECTIONS = [
    ("power",    "Alimentazione"),
    ("display",  "Display"),
    ("audio",    "Audio"),
    ("storage",  "MicroSD"),
    ("controls", "Controlli"),
    ("usb",      "USB dati"),
    ("mcu",      "MCU"),
]

# First matching pattern wins. USB_CC1/2 belong to power, not usb-data:
# the CC pulldowns advertise charge current, they never carry data.
SECTION_LAW = [
    ("controls", r"^BTN_|^MENU_K$"),
    ("display",  r"^LCD_|^LED_BLA$"),  # LED_BLA: backlight anode after R27
    ("storage",  r"^SD_"),
    ("audio",    r"^I2S_|^PAM_|^SPK"),
    ("usb",      r"^USB_D"),
    # mcu comes BEFORE power so LED6_RA is claimed here. LED1/2/3/4/5_RA are
    # passive rail-indicator junctions and belong to power; LED6_RA hangs off
    # LED_HB, a firmware-driven GPIO15 output carrying blink codes, so it and
    # its resistor R31 belong to the MCU. Without this ordering R31 ties 1-1
    # between the two sections and the generator refuses to guess.
    ("mcu",      r"^EN$|^LED_HB$|^LED6_RA$"),
    ("power",    r"^USB_CC|^VBUS(_IN)?$|^BAT|^LX$|^IP5306_|^RPP_|^LED\d+_RA$|^BUCK_"),
]

# A component follows the majority of its section-owned nets. These refs
# are the ones a vote gets wrong, each with the reason it is special:
REF_SECTION_OVERRIDES = {
    "U1": "mcu",        # ESP32 module touches every subsystem; it IS the MCU
    "J1": "power",      # USB-C receptacle: its primary role here is charge input
    "SW16": "power",  # bridges BAT+ to BTN_SELECT, but it is the power switch
}

NO_SECTION_REF = re.compile(r"^FID\d+$")   # fiducials carry no copper


def classify_sections(components, net_name):
    """(net id -> section, ref -> section); unclassifiable is a hard error."""
    net_sec, unknown = {}, []
    for nid, name in net_name.items():
        if nid == 0 or name in RAIL_NETS:
            continue
        for sec, pat in SECTION_LAW:
            if re.search(pat, name):
                net_sec[nid] = sec
                break
        else:
            unknown.append(name)
    if unknown:
        print(f"ERROR: {len(unknown)} net(s) match no SECTION_LAW pattern "
              f"and are not rails: {', '.join(sorted(unknown))}")
        print("       Add a pattern (or a rail entry) in "
              "scripts/generate_net_explorer.py — no default bucket.")
        raise SystemExit(2)

    ref_sec, ambiguous = {}, []
    for c in components:
        ref = c["ref"]
        if ref in REF_SECTION_OVERRIDES:
            ref_sec[ref] = REF_SECTION_OVERRIDES[ref]
            continue
        if NO_SECTION_REF.match(ref):
            continue
        votes = {}
        for p in c["pads"]:
            sec = net_sec.get(p["net"])
            if sec:
                votes[sec] = votes.get(sec, 0) + 1
        if not votes:
            # Every pad on a rail or GND: decoupling / bulk capacitance —
            # that is power delivery.
            ref_sec[ref] = "power"
            continue
        best = sorted(votes.items(), key=lambda kv: (-kv[1], kv[0]))
        if len(best) > 1 and best[0][1] == best[1][1]:
            ambiguous.append((ref, votes))
            continue
        ref_sec[ref] = best[0][0]
    if ambiguous:
        for ref, votes in ambiguous:
            print(f"ERROR: {ref} ties between sections {votes} — "
                  f"add it to REF_SECTION_OVERRIDES with a reason.")
        raise SystemExit(2)
    return net_sec, ref_sec


def clearance_report(cache):
    """Where different nets come closest — the short-circuit risk map.

    This does not implement its own clearance maths. It imports the same
    functions `verify_copper_clearance.py` uses, so the numbers the
    explorer draws are by construction the numbers the gate enforces —
    a second engine would eventually disagree with the first, and then
    nobody would know which one to believe.

    The geometry is copper-edge to copper-edge, per layer, over tracks,
    pads and vias (a via and a THT pad exist on every copper layer, so
    hole-adjacent copper is included). JLCDFM measures mask aperture to
    mask aperture instead, subtracting ~0.05 mm of mask expansion per
    side, so it sees roughly 0.10 mm less than these figures.
    """
    import verify_copper_clearance as CC

    nets = {n["id"]: n["name"] for n in cache["nets"]}
    layers, worst = [], []
    for layer in COPPER_LAYERS:
        feats = CC.build_layer_features(cache, layer)
        merged = CC.merge_by_net(feats)
        gaps = CC.find_gaps(merged, nets, threshold=CC.GAP_WARN)
        rows = []
        for gap, na, nb, ax, ay, bx, by in gaps:
            rows.append({
                "layer": layer, "gap": round(gap, 4),
                "a": na, "b": nb,
                "x": round((ax + bx) / 2, 3), "y": round((ay + by) / 2, 3),
                "severity": "danger" if gap < CC.GAP_DANGER else "warn",
                # find_gaps labels one side "<net> (same-net)" when the two
                # sub-polygons carry the same net — a fab dry-film risk,
                # not an electrical short.
                "sameNet": "(same-net)" in na or "(same-net)" in nb,
            })
        worst.extend(rows)
        layers.append({
            "layer": layer,
            "features": len(feats),
            "nets": len(merged),
            "danger": sum(1 for r in rows if r["severity"] == "danger"),
            "warn": sum(1 for r in rows if r["severity"] == "warn"),
        })
    worst.sort(key=lambda r: r["gap"])
    return {"dangerMm": CC.GAP_DANGER, "warnMm": CC.GAP_WARN,
            "layers": layers, "violations": worst}


def _pad_sort_key(p):
    """Deterministic, human order: numeric pin numbers sort numerically."""
    num = str(p["num"])
    return (p["ref"], 0, int(num), "") if num.isdigit() \
        else (p["ref"], 1, 0, num)


def merge_through_pads(pads):
    """Collapse a through-hole pad's per-layer copies into one pad.

    `pcb_cache` emits one entry per copper layer a pad touches, so a THT
    pad on a 4-layer board appears up to four times. That is right for a
    clearance check — each layer really does have copper there — but wrong
    for an explorer: J1 pin 13 was listed four times, and the "Pad" count
    on every connector was inflated.

    It also made the output order unstable. The per-layer copies are
    identical apart from `layer`, so any sort keyed on the pad number left
    them tied, and their relative order came from whatever the cache
    happened to emit — enough to make two runs differ and the freshness
    check cry stale for no reason.
    """
    merged = {}
    for p in pads:
        k = (p["ref"], str(p["num"]), p["x"], p["y"], p["w"], p["h"], p["type"])
        if k in merged:
            merged[k]["layers"].append(p["layer"])
        else:
            q = dict(p)
            q["layers"] = [p["layer"]]
            merged[k] = q
    out = []
    for q in merged.values():
        q["layers"] = sorted(set(q["layers"]),
                             key=lambda l: COPPER_LAYERS.index(l)
                             if l in COPPER_LAYERS else 99)
        q["layer"] = q["layers"][0]        # primary layer, for colouring
        out.append(q)
    return sorted(out, key=_pad_sort_key)


def dangling_ends(cache, net_name):
    """Track endpoints that reach nothing — copper that stops in the air.

    No existing gate sees these. `verify_net_connectivity` asks whether a
    net is ONE connected component; a stub hanging off a routed net is
    still part of that one component, so it passes. KiCad DRC reports
    unconnected *pads*, and these stubs leave no pad unconnected. The
    result is copper that goes nowhere and nothing complains.

    An endpoint is fine when it is a junction with another segment, lands
    on a via or a pad of its own net, or ends inside its own zone fill on
    the same layer. Anything else is a dead end.
    """
    from shapely.geometry import Point

    key = lambda x, y: (round(x, 3), round(y, 3))  # noqa: E731

    degree = {}
    for s in cache["segments"]:
        for x, y in ((s["x1"], s["y1"]), (s["x2"], s["y2"])):
            k = (s["net"], s["layer"], key(x, y))
            degree[k] = degree.get(k, 0) + 1

    vias = {}
    for v in cache["vias"]:
        vias.setdefault(v["net"], set()).add(key(v["x"], v["y"]))

    pads = {}
    for p in cache["pads"]:
        if p["net"]:
            pads.setdefault(p["net"], []).append(
                (p["x"], p["y"], p["w"], p["h"]))

    zones = {}
    for z in zone_geometry():
        zones.setdefault((z["net"], z["layer"]), []).extend(z["polys"])

    out = []
    for (net, layer, (x, y)), deg in degree.items():
        if deg > 1:
            continue
        if key(x, y) in vias.get(net, ()):
            continue
        # 0.06 mm slack: endpoints are placed at pad centres or edges, and
        # the cache rounds. Anything further is not touching the pad.
        if any(abs(x - px) <= pw / 2 + 0.06 and abs(y - py) <= ph / 2 + 0.06
               for px, py, pw, ph in pads.get(net, ())):
            continue
        polys = zones.get((net_name.get(net, ""), layer), ())
        if any(poly.buffer(0).contains(Point(x, y)) for poly in polys):
            continue
        out.append({"net": net_name.get(net, "?"), "netId": net,
                    "layer": layer, "x": x, "y": y})
    return sorted(out, key=lambda d: (d["net"], d["x"], d["y"]))


def zone_geometry():
    """Real poured copper, island by island, holes included.

    pcb_cache only counts filled_polygon blocks; pcb_copper_graph parses
    them into Shapely polygons. Reuse it rather than writing a third
    zone parser.
    """
    import pcb_copper_graph

    return pcb_copper_graph.parse_copper(PCB).zones


# ── footprint metadata + board outline (parsed from the .kicad_pcb) ───

def _balanced(text, start):
    """Return the span of the s-expression whose '(' sits at `start`."""
    depth, i, in_str = 0, start, False
    while i < len(text):
        ch = text[i]
        if in_str:
            if ch == "\\":
                i += 2
                continue
            if ch == '"':
                in_str = False
        elif ch == '"':
            in_str = True
        elif ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return text[start:i + 1]
        i += 1
    return text[start:]


def parse_footprints(text):
    """ref -> {footprint, value, side, x, y, rot}."""
    out = {}
    for m in re.finditer(r'\(footprint\s+"([^"]+)"\s+\(at\s+'
                         r'(-?[\d.]+)\s+(-?[\d.]+)(?:\s+(-?[\d.]+))?\)', text):
        body = _balanced(text, m.start())
        ref = re.search(r'\(property\s+"Reference"\s+"([^"]*)"', body)
        if not ref:
            ref = re.search(r'\(fp_text\s+reference\s+"([^"]*)"', body)
        if not ref:
            continue
        val = re.search(r'\(property\s+"Value"\s+"([^"]*)"', body)
        if not val:
            val = re.search(r'\(fp_text\s+value\s+"([^"]*)"', body)
        # The footprint's own (layer ...) — first one after the (at ...).
        lay = re.search(r'\(layer\s+"(F\.Cu|B\.Cu)"\)', body)
        out[ref.group(1)] = {
            "footprint": m.group(1),
            "value": val.group(1) if val else "",
            "side": "B" if (lay and lay.group(1) == "B.Cu") else "F",
            "x": float(m.group(2)),
            "y": float(m.group(3)),
            "rot": float(m.group(4)) if m.group(4) else 0.0,
        }
    return out


def parse_outline(text):
    """Edge.Cuts primitives, as flat segments/arcs for the SVG."""
    edges = []
    for m in re.finditer(
            r'\(gr_line\s+\(start\s+(-?[\d.]+)\s+(-?[\d.]+)\)\s+'
            r'\(end\s+(-?[\d.]+)\s+(-?[\d.]+)\)(.*?)\)\s*(?=\(gr_|\Z)',
            text, re.S):
        if '"Edge.Cuts"' in m.group(5):
            edges.append({"type": "line",
                          "x1": float(m.group(1)), "y1": float(m.group(2)),
                          "x2": float(m.group(3)), "y2": float(m.group(4))})
    for m in re.finditer(
            r'\(gr_arc\s+\(start\s+(-?[\d.]+)\s+(-?[\d.]+)\)\s+'
            r'\(mid\s+(-?[\d.]+)\s+(-?[\d.]+)\)\s+'
            r'\(end\s+(-?[\d.]+)\s+(-?[\d.]+)\)(.*?)\)\s*(?=\(gr_|\Z)',
            text, re.S):
        if '"Edge.Cuts"' in m.group(7):
            edges.append({"type": "arc",
                          "x1": float(m.group(1)), "y1": float(m.group(2)),
                          "xm": float(m.group(3)), "ym": float(m.group(4)),
                          "x2": float(m.group(5)), "y2": float(m.group(6))})
    return edges


# ── build ────────────────────────────────────────────────────────────

def main():
    from pcb_cache import load_cache

    cache = load_cache()
    text = open(PCB).read()
    fps = parse_footprints(text)
    edges = parse_outline(text)

    net_name = {n["id"]: n["name"] for n in cache["nets"]}
    net_types = cache.get("net_types", {})

    # Components. A ref with no parsed footprint still gets an entry built
    # from its pads, so nothing silently vanishes from the explorer.
    pads_by_ref = {}
    for p in merge_through_pads(cache["pads"]):
        pads_by_ref.setdefault(p["ref"], []).append(p)

    components = []
    for ref in sorted(pads_by_ref):
        meta = fps.get(ref)
        pads = pads_by_ref[ref]
        if meta is None:
            # Fall back to the pad cloud: side from the pad layers.
            back = sum(1 for p in pads if p["layer"] == "B.Cu")
            front = sum(1 for p in pads if p["layer"] == "F.Cu")
            meta = {
                "footprint": "?", "value": "",
                "side": "B" if back > front else "F",
                "x": pads[0].get("fp_x", pads[0]["x"]),
                "y": pads[0].get("fp_y", pads[0]["y"]),
                "rot": 0.0,
                "unparsed": True,
            }
        components.append({
            "ref": ref,
            "value": meta["value"],
            "footprint": meta["footprint"],
            "side": meta["side"],
            "x": meta["x"], "y": meta["y"], "rot": meta["rot"],
            "unparsed": meta.get("unparsed", False),
            "pads": [
                {"num": p["num"], "net": p["net"], "x": p["x"], "y": p["y"],
                 "w": p["w"], "h": p["h"], "shape": p["shape"],
                 "layer": p["layer"], "layers": p["layers"],
                 "type": p["type"], "drill": p["drill"]}
                for p in pads
            ],
        })

    # Nets, each carrying the refs it touches so the UI can answer
    # "where does this go?" without walking geometry in the browser.
    net_pads = {}
    for p in merge_through_pads(cache["pads"]):
        if p["net"]:
            net_pads.setdefault(p["net"], []).append(
                {"ref": p["ref"], "num": p["num"], "x": p["x"], "y": p["y"],
                 "layer": p["layer"], "layers": p["layers"],
                 "type": p["type"]})

    seg_by_net, via_by_net = {}, {}
    for s in cache["segments"]:
        seg_by_net.setdefault(s["net"], []).append(s)
    for v in cache["vias"]:
        via_by_net.setdefault(v["net"], []).append(v)

    zone_nets = {}
    for z in cache["zones"]:
        zone_nets.setdefault(z["net"], []).append(z["layer"])

    # Poured copper. In1.Cu and In2.Cu carry NO routed tracks at all — they
    # are solid planes — so without the fill geometry those two layer
    # toggles show an empty board and read as broken. The fill also has to
    # be the REAL poured shape, holes included: the clearance holes around
    # every via and pad are what makes a plane legible as a plane.
    zone_fills = []
    for z in zone_geometry():
        for poly in z["polys"]:
            simple = poly.simplify(ZONE_SIMPLIFY_MM, preserve_topology=True)
            zone_fills.append({
                "net": z["net"],
                "layer": z["layer"],
                "priority": z["priority"],
                "outer": [[round(x, 3), round(y, 3)]
                          for x, y in simple.exterior.coords],
                "holes": [[[round(x, 3), round(y, 3)] for x, y in r.coords]
                          for r in simple.interiors],
                "area": round(poly.area, 1),
            })

    nets = []
    for nid, name in sorted(net_name.items()):
        if nid == 0:
            continue
        segs = seg_by_net.get(nid, [])
        length = sum(((s["x2"] - s["x1"]) ** 2 +
                      (s["y2"] - s["y1"]) ** 2) ** 0.5 for s in segs)
        layers = sorted({s["layer"] for s in segs} | set(zone_nets.get(nid, [])))
        nets.append({
            "id": nid,
            "name": name,
            "type": net_types.get(name, "signal"),
            "pads": net_pads.get(nid, []),
            "segments": segs,
            "vias": via_by_net.get(nid, []),
            "zoneLayers": sorted(set(zone_nets.get(nid, []))),
            "layers": layers,
            "length": round(length, 2),
        })

    # Unrouted pads (net 0) are worth showing, not hiding.
    unnetted = [{"ref": p["ref"], "num": p["num"]}
                for p in merge_through_pads(cache["pads"]) if not p["net"]]

    net_sec, ref_sec = classify_sections(components, net_name)
    sections = [{
        "id": sid, "label": label,
        "nets": sorted(n for n, s in net_sec.items() if s == sid),
        "refs": sorted(r for r, s in ref_sec.items() if s == sid),
    } for sid, label in SECTIONS]

    data = {
        "generatedFrom": os.path.basename(PCB),
        "pcbHash": cache.get("pcb_hash", "")[:12],
        "stats": cache.get("stats", {}),
        "copperLayers": COPPER_LAYERS,
        "outline": edges,
        "zoneFills": zone_fills,
        "components": components,
        "nets": nets,
        "unnettedPads": unnetted,
        "danglingEnds": dangling_ends(cache, net_name),
        "clearance": clearance_report(cache),
        "sections": sections,
        "railNets": sorted(nid for nid, name in net_name.items()
                           if name in RAIL_NETS),
    }

    payload = json.dumps(data, separators=(",", ":"))
    rel = os.path.relpath(OUT, PROJECT_DIR)

    if "--check" in sys.argv:
        if not os.path.exists(OUT):
            print(f"STALE: {rel} is missing — run `make net-explorer`")
            return 1
        if open(OUT).read() != payload:
            print(f"STALE: {rel} does not match "
                  f"{os.path.relpath(PCB, PROJECT_DIR)} — "
                  f"a track, placement or BOM field moved. "
                  f"Run `make net-explorer`.")
            return 1
        print(f"OK: {rel} matches the board at {data['pcbHash']}")
        return 0

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write(payload)

    unparsed = [c["ref"] for c in components if c["unparsed"]]
    print(f"  Wrote {rel} ({os.path.getsize(OUT) / 1024:.0f} kB)")
    print(f"    {len(components)} components "
          f"({sum(1 for c in components if c['side'] == 'F')} front / "
          f"{sum(1 for c in components if c['side'] == 'B')} back)")
    print(f"    {len(nets)} nets, {len(cache['segments'])} segments, "
          f"{len(cache['vias'])} vias, {len(edges)} outline primitives")
    print(f"    {len(zone_fills)} zone fill islands "
          f"({sum(len(z['holes']) for z in zone_fills)} clearance holes)")
    print("    sections: " + ", ".join(
        f"{s['id']} {len(s['nets'])}n/{len(s['refs'])}c" for s in sections))
    cl = data["clearance"]
    nd = sum(l["danger"] for l in cl["layers"])
    nw = sum(l["warn"] for l in cl["layers"])
    print(f"    clearance: {nd} DANGER (<{cl['dangerMm']}mm), "
          f"{nw} WARN (<{cl['warnMm']}mm)")
    if nd:
        print("    WARN  different-net copper below the fab minimum — "
              "see verify_copper_clearance.py")
    if data["danglingEnds"]:
        print(f"    WARN  {len(data['danglingEnds'])} dangling track ends "
              f"(copper that reaches nothing) — see verify_dangling_copper.py")
    if unnetted:
        print(f"    {len(unnetted)} pads on no net (shown as unrouted)")
    if unparsed:
        print(f"    WARN  {len(unparsed)} refs had no parsable footprint "
              f"header, side inferred from pads: {', '.join(unparsed[:8])}")
    if not edges:
        print("    WARN  no Edge.Cuts outline found — board frame will be "
              "derived from the pad bounding box")
    return 0


if __name__ == "__main__":
    sys.exit(main())
