#!/usr/bin/env python3
"""Generate the docs BOM table from release_jlcpcb/bom.csv — the shipped BOM.

The table in website/docs/design/components.md was hand-maintained and had
drifted badly: it still listed the AMS1117 LDO and a C2 tantalum that no
longer exist, and it was missing U4, D1, Q1, L2, C29, C30, R22/R23, R24/R25
and R26 entirely. A hand-copied BOM is a second source of truth, and this
repo has already been bitten by that class of bug.

So the table is generated from the CSV that actually goes to JLCPCB, injected
between markers in the Markdown. Role descriptions live in _ROLES below,
keyed by LCSC part number — the one thing a CSV cannot tell you. Datasheet
links are discovered by matching the `_C<digits>.pdf` suffix of the files in
website/static/datasheets/, so adding a PDF is enough to link it.

`--check` fails when the rendered table differs from what is committed, so
the release pipeline can keep the docs honest.

Usage:
    python3 scripts/generate_docs_bom.py
    python3 scripts/generate_docs_bom.py --check
"""

from __future__ import annotations

import csv
import re
import sys
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
BOM = BASE / "release_jlcpcb" / "bom.csv"
DOC = BASE / "website" / "docs" / "design" / "components.md"
DATASHEETS = BASE / "website" / "static" / "datasheets"

START = "<!-- BOM:START — generated by scripts/generate_docs_bom.py -->"
END = "<!-- BOM:END -->"

# What the part DOES on this board. A CSV cannot carry intent, so this is the
# only hand-maintained piece — keyed by LCSC so it survives ref renumbering.
_ROLES = {
    "C2913202": "ESP32-S3-WROOM-1-N16R8 — 16 MB flash, 8 MB octal PSRAM",
    "C181692": "IP5306 — charger + 5 V boost, charge-and-play",
    "C78988": "SY8089AAAC — 2 A synchronous buck, 5 V → 3.3 V (~93 %)",
    "C5122557": "PAM8403 — class-D audio amplifier",
    "C2765186": "USB-C receptacle, 16-pin",
    "C91145": "microSD slot (TF-01A) — ROM storage",
    "C295747": "JST PH battery connector",
    "C2856812": "FPC 40-pin 0.5 mm — ILI9488 display",
    "C7519": "USBLC6-2SC6 — USB ESD/TVS protection",
    "C37704": "BAT54C — dual Schottky, menu-combo diode OR",
    "C15127": "AO3401A — Q1 reverse-battery protection, Q2 +5V high-side load switch (R32: replaced SI2301CDS C10487, whose 2.3 A rating sat below the battery-path current)",
    "C431540": "SW16 slide switch (MSK12C02) — drives Q2's gate; carries no rail current",
    "C318884": "tact switches — D-pad, ABXY, Start/Select, L/R, Menu, RST, BOOT",
    "C84256": "red LED (LED1) — power indicator on +3V3 (U2's LED pins are NC)",
    "C19171391": "red LED — LED2 power indicator / LED3-6 diagnostics; YLED0805R is red despite the old 'green' label",
    "C280579": "L1 — IP5306 boost inductor",
    "C36409": "L2 — SY8089 buck output inductor",
    "C27834": "CC1/CC2 pull-downs — USB-C UFP detection",
    "C17414": "button pull-ups + R3 EN pull-up (R25-CRIT-1 fix)",
    "C17955": "R27 — backlight series resistor, +5V -> LED_BLA (R25-HIGH-1 fix)",
    "C960026": "F1 — VBUS PTC fuse, 2A hold / 4A trip (R3-HIGH-4 fix)",
    "C4328": "PAM8403 INL/INR input bias",
    "C149504": "R24 Q1 gate pull-down, R25 buck feedback (upper) — R16 deleted in the SW16 respin",
    "C17560": "R26 buck feedback (lower), R32 Q2 gate pull-up (default OFF)",
    "C17513": "R17/R18 LED series resistors + R33 Q2 series gate resistor (soft-start slope)",
    "C25092": "USB D+/D- series termination",
    "C1804": "C29 — buck feedback feedforward",
    "C49678": "decoupling + C31 EN reset cap (R25-CRIT-1 fix)",
    "C13967": "C22 — DC-blocking into PAM8403",
    "C28323": "PAM8403 VDD/PVDD decoupling + C32 Q2 gate-source soft-start cap",
    "C1779": "C33 — IP5306 KEY wake cap (couples the SW16 ON transition into KEY)",
    "C720477": "SW17 — manual KEY wake, DO NOT PLACE (fit only if the C33 pulse is short)",
    "C15850": "bulk decoupling",
    "C12891": "C1 buck input, C19 boost output, C30 buck output",
}


def _datasheets() -> dict[str, str]:
    """LCSC part number -> public URL of its datasheet, if one is present."""
    out: dict[str, str] = {}
    if not DATASHEETS.is_dir():
        return out
    for f in DATASHEETS.glob("*.pdf"):
        m = re.search(r"_(C\d+)\.pdf$", f.name)
        if m:
            out[m.group(1)] = f"/datasheets/{f.name}"
    return out


def build() -> str:
    sheets = _datasheets()
    rows = []
    with open(BOM, newline="", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            lcsc = r["LCSC Part #"].strip()
            refs = r["Designator"].strip().strip('"')
            link = sheets.get(lcsc)
            rows.append((
                refs,
                r["Comment"].strip(),
                r["Footprint"].strip(),
                lcsc,
                r["Quantity"].strip(),
                _ROLES.get(lcsc, ""),
                f"[PDF]({link})" if link else "—",
            ))

    total = sum(int(r[4]) for r in rows)
    lines = [
        START,
        "",
        f"*{len(rows)} line items, {total} placements. Generated from "
        f"`release_jlcpcb/bom.csv` — the file uploaded to JLCPCB. "
        f"Regenerate with `make docs-bom`.*",
        "",
        "| Ref | Part | Package | LCSC | Qty | Role | Datasheet |",
        "|---|---|---|---|--:|---|---|",
    ]
    for refs, comment, fp, lcsc, qty, role, ds in rows:
        lines.append(
            f"| {refs} | {comment} | `{fp}` | "
            f"[{lcsc}](https://www.lcsc.com/product-detail/{lcsc}.html) | "
            f"{qty} | {role} | {ds} |"
        )
    lines += ["", END]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    table = build()
    text = DOC.read_text(encoding="utf-8")

    if START in text and END in text:
        new = re.sub(
            re.escape(START) + r".*?" + re.escape(END), table, text, flags=re.S)
    else:
        print(f"ERROR: markers not found in {DOC.relative_to(BASE)}.\n"
              f"Add these two lines where the table should go:\n"
              f"  {START}\n  {END}")
        return 1

    if "--check" in argv:
        if new != text:
            print(f"STALE: {DOC.relative_to(BASE)} does not match "
                  f"{BOM.relative_to(BASE)} — run `make docs-bom`")
            return 1
        print(f"OK: {DOC.relative_to(BASE)} matches the shipped BOM")
        return 0

    DOC.write_text(new, encoding="utf-8")
    n = table.count("\n| ") - 1
    print(f"Wrote the BOM table into {DOC.relative_to(BASE)} ({n} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
