#!/usr/bin/env python3
"""Generate docs/REPO_MAP.md — one line per script, so nobody greps 447k tokens.

Metric M3 in scripts/context_budget.py: without an index, answering "which
script checks X?" means grepping the whole Python surface. With it, the same
answer costs one small read.

The map is GENERATED, never hand-written, so it cannot drift from the code.
Each entry carries only what is needed to choose a script:

  * the first line of its module docstring (what it does)
  * whether it is a gate (exits non-zero on failure) or a tool
  * the `make` target that runs it, if any
  * its size, so a reader knows what opening it will cost

Regenerate with `make repo-map`; `--check` fails if it is stale, so CI and
the release pipeline can keep it honest.

Usage:
    python3 scripts/generate_repo_map.py
    python3 scripts/generate_repo_map.py --check
"""

from __future__ import annotations

import ast
import glob
import os
import re
import sys
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
OUT = BASE / "docs" / "REPO_MAP.md"

SKIP_DIRS = ("__pycache__", ".easyeda_cache", ".claude/worktrees")

# A script that calls sys.exit with a non-zero/derived status is a gate:
# it can fail a pipeline. Everything else only reports.
_GATE_HINTS = ("sys.exit(1", "sys.exit(2", "sys.exit(bad", "sys.exit(fail",
               "sys.exit(1 if", "unittest.main", "exit_code", "return 1")


def _docline(path: Path) -> str:
    try:
        tree = ast.parse(path.read_text(errors="replace"))
    except SyntaxError:
        return "(unparseable)"
    doc = ast.get_docstring(tree)
    if not doc:
        return ""
    return doc.strip().split("\n", 1)[0].rstrip(".")


def _is_gate(path: Path) -> bool:
    text = path.read_text(errors="replace")
    return any(h in text for h in _GATE_HINTS)


def _make_targets() -> dict[str, str]:
    """Map script filename -> make target that runs it."""
    mk = BASE / "Makefile"
    if not mk.exists():
        return {}
    out: dict[str, str] = {}
    target = None
    for line in mk.read_text().splitlines():
        m = re.match(r"^([a-zA-Z0-9_-]+):", line)
        if m:
            target = m.group(1)
        for s in re.findall(r"scripts/([\w/]+\.py)", line):
            name = os.path.basename(s)
            if target and name not in out:
                out[name] = target
    return out


def build() -> str:
    targets = _make_targets()
    groups: dict[str, list] = {}
    for p in sorted(glob.glob(str(BASE / "scripts" / "**" / "*.py"),
                              recursive=True)):
        path = Path(p)
        rel = str(path.relative_to(BASE))
        if any(s in rel for s in SKIP_DIRS) or path.name == "__init__.py":
            continue
        pkg = str(path.parent.relative_to(BASE))
        groups.setdefault(pkg, []).append((
            rel, _docline(path), _is_gate(path),
            targets.get(path.name, ""), round(path.stat().st_size / 4),
        ))

    total = sum(e[4] for v in groups.values() for e in v)
    n = sum(len(v) for v in groups.values())

    lines = [
        "# Repo map — scripts",
        "",
        "<!-- GENERATED by scripts/generate_repo_map.py — do not edit. -->",
        "<!-- Regenerate: make repo-map    Verify: make repo-map-check -->",
        "",
        f"{n} scripts, ~{total:,} tokens of source. This index exists so that",
        "finding the right one costs a single read instead of a repo-wide grep.",
        "",
        "**gate** = exits non-zero on failure, so it can block a pipeline.",
        "**~tok** = cost of opening the file, in tokens.",
        "",
    ]
    for pkg in sorted(groups):
        lines += [f"## `{pkg}/`", "",
                  "| script | gate | make | ~tok | purpose |",
                  "|---|:--:|---|--:|---|"]
        for rel, doc, gate, target, size in sorted(groups[pkg]):
            name = os.path.basename(rel)
            tgt = f"`{target}`" if target else ""
            lines.append(
                f"| `{name}` | {'✅' if gate else ''} | {tgt} | {size:,} | "
                f"{doc or '—'} |")
        lines.append("")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    content = build()
    if "--check" in argv:
        if not OUT.exists():
            print(f"MISSING: {OUT.relative_to(BASE)} — run `make repo-map`")
            return 1
        if OUT.read_text() != content:
            print(f"STALE: {OUT.relative_to(BASE)} does not match the scripts "
                  f"on disk — run `make repo-map`")
            return 1
        print(f"OK: {OUT.relative_to(BASE)} is current")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content)
    print(f"Wrote {OUT.relative_to(BASE)} "
          f"(~{round(len(content) / 4):,} tokens)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
