#!/usr/bin/env python3
"""Emit hardware/enclosure/pcb_parts.scad — the PCB, to the millimetre, for
the enclosure model.

The enclosure used to carry a hand-drawn PCB model (a dozen boxes at
remembered positions). It drifted: the shell was designed around a JST
connector that was 3 mm shorter than the real one and around a display
zone that was never the panel. This generator reads the SAME placement
list JLCPCB assembles from (`jlcpcb_export._build_placements`, 98 fitted
parts + the DNP SW17 and the speaker pads) and the board constants, and
writes them as OpenSCAD data:

    pcb_parts = [ [ref, x, y, rot, side, L, W, H], ... ]   enclosure coords
    pcb_slot  = [cx, cy, w, h]                             FPC slot
    pcb_holes = [[x, y, d], ...]                           mounting holes

Body sizes come from BODY_BY_PACKAGE (package -> L x W x H in mm, before
rotation; H = height above the board face), each row citing its source.
A package missing from the table is a hard error, never a guess: an
unknown body cannot be checked against the battery or the shell.

`--check` exits 1 when the committed file is stale (verify_enclosure_sync
runs this, so a placement moved in board.py without regenerating the scad
is a red gate, not a silent drift).
"""

from __future__ import annotations

import sys
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE))

OUT = BASE / "hardware" / "enclosure" / "pcb_parts.scad"

# package -> (L along the footprint X, W along Y, H above the board face)
# "ds" = the datasheet in hardware/datasheets or website/static/datasheets
BODY_BY_PACKAGE = {
    "SW-SMD-5.1x5.1":   (5.1, 5.1, 1.5),    # TS-1187A code A (ds C318884)
    "SW-SMD-2P-TS1088": (3.9, 3.0, 1.6),    # TS-1088 (DNP land)
    "LED_0805":         (2.0, 1.25, 0.8),   # 0805 LED
    "R_0805":           (2.0, 1.25, 0.7),
    "C_0805":           (2.0, 1.25, 1.25),  # 10 uF 0805 can be 1.25 thick
    "C_1206":           (3.2, 1.6, 1.6),    # 22 uF 1206 (ds C12891 T max)
    "R_1206":           (3.2, 1.6, 0.6),
    "R_0402":           (1.0, 0.5, 0.4),
    "F_1812":           (4.5, 3.2, 1.6),    # PTC 1812
    "SOT-23":           (2.9, 1.6, 1.2),
    "SOT-23-3":         (2.9, 1.6, 1.2),
    "SOT-23-5":         (2.9, 1.6, 1.3),    # SY8089 (ds C78988)
    "SOT-23-6":         (2.9, 1.6, 1.3),    # USBLC6
    "ESOP-8":           (5.0, 4.0, 1.6),    # IP5306 (ds C181692)
    "SOP-16":           (10.0, 4.0, 1.75),  # PAM8403 (ds C5122557)
    "SMD-4x4x2":        (4.0, 4.0, 2.0),    # L1 (ds C280579)
    "IND-SMD-4.0x4.0":  (4.0, 4.0, 3.0),    # L2 SWPA4030 (C36409)
    "Module_ESP32-S3":  (25.5, 18.0, 3.1),  # WROOM-1 ds section 10
    "FPC-40P-0.5mm":    (26.0, 3.5, 2.0),   # J4 C2856812 (40P body ~26 x 3.5)
    "USB-C-SMD-16P":    (8.94, 7.35, 3.2),  # GCT USB4105 (ds C2765186)
    "TF-01A":           (14.5, 15.0, 1.9),  # micro SD push-pull (ds C91145)
    "SS-12D00G3":       (8.6, 3.7, 2.0),    # MSK12C02 body (ds C431540)
    "JST-PH-2P-SMD":    (7.9, 8.6, 5.5),    # S2B-PH-SM4-TB, JST p.4 side entry
    "Speaker-28mm":     (0.0, 0.0, 0.0),    # solder pads only — driver is off-board
    "Fiducial":         (0.0, 0.0, 0.0),
}


def parts() -> list:
    """[(ref, x, y, rot, side, L, W, H), ...] in enclosure coords."""
    from scripts.generate_pcb import board as B
    from scripts.generate_pcb.jlcpcb_export import _build_placements

    rows = []
    missing = set()
    for ref, _val, pkg, x, y, rot, layer in _build_placements():
        body = BODY_BY_PACKAGE.get(pkg)
        if body is None:
            missing.add(pkg)
            continue
        if body[2] <= 0:
            continue                      # pads-only footprints
        ex, ey = x - B.CX, B.CY - y       # enclosure coords (Y up)
        side = "top" if layer == "top" else "bottom"
        rows.append((ref, ex, ey, float(rot), side, *body))
    if missing:
        raise SystemExit("packages without a body in BODY_BY_PACKAGE: "
                         + ", ".join(sorted(missing)))
    rows.sort(key=lambda r: (r[4], r[0]))
    return rows


def build() -> str:
    from scripts.generate_pcb import board as B

    rows = parts()
    lines = [
        "// GENERATED by scripts/generate_enclosure_pcb.py — do not edit.",
        "// Source: scripts/generate_pcb/board.py placements "
        "(jlcpcb_export._build_placements) + BODY_BY_PACKAGE.",
        "// Enclosure coords: origin = board centre, Y up. rot = KiCad angle.",
        "// Row: [ref, x, y, rot, side, L, W, H]; H = height above that face.",
        "",
        f"pcb_outline = [{B.BOARD_W}, {B.BOARD_H}, {B.CORNER_R}];",
        f"pcb_slot = [{B.FPC_SLOT_ENC[0]}, {B.FPC_SLOT_ENC[1]}, "
        f"{B.FPC_SLOT_W}, {B.FPC_SLOT_H}];",
        "pcb_holes = [" + ", ".join(f"[{x}, {y}, 2.5]"
                                     for x, y in B.MOUNT_HOLES_ENC) + "];",
        "pcb_parts = [",
    ]
    for ref, ex, ey, rot, side, L, W, H in rows:
        lines.append(f'    ["{ref}", {ex:g}, {ey:g}, {rot:g}, "{side}", '
                     f'{L:g}, {W:g}, {H:g}],')
    lines.append("];")
    return "\n".join(lines) + "\n"


def main(argv) -> int:
    text = build()
    if "--check" in argv:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"STALE: {OUT.relative_to(BASE)} does not match board.py — "
                  "run `python3 scripts/generate_enclosure_pcb.py`")
            return 1
        print(f"FRESH: {OUT.relative_to(BASE)}")
        return 0
    OUT.write_text(text)
    n = text.count("\n    [")
    print(f"wrote {OUT.relative_to(BASE)}: {n} parts")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
